server:
  port: 8080

spring:
  application:
    name: employee-management
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: Okay@4262
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    database-platform: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    region:
      static: ap-south-1
    credentials:
      access-key:
      secret-key: